os: linux
language: python
python:
  - 2.7

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7
    osx_image: xcode8

before_install:
  - which python
  - brew uninstall --ignore-dependencies python
  - brew install python@2 --universal --framework
  - export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
  - which python
  - export VERSIONER_PYTHON_PREFER_32_BIT=yes
  - defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
  - which python
  - python --version

install:
  # Install wheel, upgrade pip to use wheel-cache
  - python -m pip install -U pip
  - python -m easy_install -U setuptools

  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  # Install dependencies.
  - pip install -r requirements.txt | cat

  # Install dependencies for tests.
#  - pip install -r tests/requirements.txt | cat

  - pip install git+http://github.com/pyinstaller/pyinstaller

  # Install qt4 from third-party source
  # https://github.com/cartr/homebrew-qt4
#  - brew tap cartr/qt4
#  - brew tap-pin cartr/qt4
#  - brew install cartr/qt4/qt
#  - brew install pyside@1.2 pyside-tools@1.2

  # where are libs?
#  - python -c 'from PySide.QtCore import QCoreApplication;app = QCoreApplication([]);print([str(p) for p in app.libraryPaths()])'

  # - brew install pyside pyside-tools

  # Install mcedit.
  #- python setup.py develop

script:
  #- if [ "${TRAVIS_TAG}x" = "x" ]; then return 0; fi
  #- export MCEDIT_BUILD_VERSION=${TRAVIS_TAG}
  - pyinstaller main-osx.spec
  - zip -r "Test_${TRAVIS_BUILD_NUMBER}.zip" "dist" -x "*.DS_Store"


# Deploy to GitHub Releases
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: Test_$TRAVIS_BUILD_NUMBER.zip
  name: "Build #$TRAVIS_BUILD_NUMBER"
  file_glob: true
  skip_cleanup: true